#!/bin/sh

set -eu

"$(dirname "$0")/test-aic"
if [ "$(uname -s)" != "Darwin" ]; then exec swift test "$@"; fi

developer_dir=$(xcode-select --print-path)

if [ "$developer_dir" = "/Library/Developer/CommandLineTools" ]; then
    framework_dir="$developer_dir/Library/Developer/Frameworks"
    library_dir="$developer_dir/Library/Developer/usr/lib"

    exec swift test \
        --disable-xctest \
        -Xswiftc -F -Xswiftc "$framework_dir" \
        -Xlinker -F -Xlinker "$framework_dir" \
        -Xlinker -rpath -Xlinker "$framework_dir" \
        -Xlinker -rpath -Xlinker "$library_dir" \
        "$@"
fi

exec swift test "$@"
